### ISSUE TITLE
update _modelchain_ac_model for multi array inverters

### ISSUE THREAD

**Issue by wholmgren** [SolarPerformanceInsight/solarperformanceinsight#109]
https://github.com/pvlib/pvlib-python/pull/1147 and https://github.com/pvlib/pvlib-python/pull/1150 changed the object oriented api for the new multi-array inverter functions. Now you just pass "sandia" or "pvwatts" and the objects determine which function they should call. So SPI needs to update `PVWattsInverterParameters._modelchain_ac_model` and `SandiaInverterParameters._modelchain_ac_model`. The change is available in `v0.9.0-alpha.2`

**Comment by alorenzo175** [comment]
We'll need to wait for https://github.com/pvlib/pvlib-python/pull/1157 otherwise we'll have to adjust the logic below to not return a list if `num_arrays == 1`

https://github.com/SolarPerformanceInsight/solarperformanceinsight/blob/0a7a476d6d4bef99565bd5fe3c44039277f03281/api/solarperformanceinsight_api/compute.py#L89-L111

**Comment by wholmgren** [comment]
Merged that PR. Do you want an alpha-3 now?

**Comment by alorenzo175** [comment]
I think there is still the issue raised in #119. I'll try and track it down and raise in pvlib
